const chatbotThemes = {
  default: {
    backgroundColor: "#f2f4f4",
    textColor: "#333",
    bubbleColor: "#007bff",
    buttonColor: "#007bff",
    borderRadius: "10px",
    botAlign: "left",
    userAlign: "right",
    botBubbleColor: "#e5e7e9",
    userBubbleColor: "#40E0D0",
    buttonTextColor: "#fff",
    buttonHoverColor: "#0056b3",
    buttonBorderRadius: "5px",
  },
  dark: {
    backgroundColor: "#333",
    textColor: "#fff",
    bubbleColor: "#222",
    buttonColor: "#ff9900",
    borderRadius: "12px",
    botAlign: "left",
    userAlign: "right",
    botBubbleColor: "#222",
    userBubbleColor: "#444",
    buttonTextColor: "#000",
    buttonHoverColor: "#e68a00",
    buttonBorderRadius: "6px",
  },
  modernGreen: {
    backgroundColor: "#ffffff",
    textColor: "#000",
    bubbleColor: "#28a745",
    buttonColor: "#28a745",
    borderRadius: "8px",
    botAlign: "left",
    userAlign: "right",
    botBubbleColor: "#28a745",
    userBubbleColor: "#d4edda",
    buttonTextColor: "#fff",
    buttonHoverColor: "#218838",
    buttonBorderRadius: "5px",
  },
  futuristicBlue: {
    backgroundColor: "#1e3a8a",
    textColor: "#ffffff",
    bubbleColor: "#3b82f6",
    buttonColor: "#60a5fa",
    borderRadius: "15px",
    botAlign: "left",
    userAlign: "right",
    botBubbleColor: "#3b82f6",
    userBubbleColor: "#9ec5fe",
    buttonTextColor: "#fff",
    buttonHoverColor: "#2563eb",
    buttonBorderRadius: "7px",
  },
  elegantPurple: {
    backgroundColor: "#4b0082",
    textColor: "#fff",
    bubbleColor: "#8a2be2",
    buttonColor: "#9932cc",
    borderRadius: "10px",
    botAlign: "left",
    userAlign: "right",
    botBubbleColor: "#8a2be2",
    userBubbleColor: "#d8bfd8",
    buttonTextColor: "#fff",
    buttonHoverColor: "#7a1fa2",
    buttonBorderRadius: "6px",
  },
  orange: {
    backgroundColor: "#ff5733",
    textColor: "#fdfefe",
    bubbleColor: "#ff5733",
    buttonColor: "#9932cc",
    borderRadius: "10px",
    botAlign: "left",
    userAlign: "right",
    botBubbleColor: "#ff5733",
    userBubbleColor: "#d8bfd8",
    buttonTextColor: "#fff",
    buttonHoverColor: "#7a1fa2",
    buttonBorderRadius: "6px",
  },
  mustard: {
    backgroundColor: "#f1c40f",
    textColor: "#fdfefe",
    bubbleColor: "#f1c40f",
    buttonColor: "#9932cc",
    borderRadius: "10px",
    botAlign: "left",
    userAlign: "right",
    botBubbleColor: "#f1c40f",
    userBubbleColor: "#f9e79f",
    buttonTextColor: "#fff",
    buttonHoverColor: "#7a1fa2",
    buttonBorderRadius: "6px",
  },
  oceanic: {
    backgroundColor: "#5dade2",
    textColor: "#fdfefe",
    bubbleColor: "#5dade2",
    buttonColor: "#9932cc",
    borderRadius: "10px",
    botAlign: "left",
    userAlign: "right",
    botBubbleColor: "#5dade2",
    userBubbleColor: "#d8bfd8",
    buttonTextColor: "#fff",
    buttonHoverColor: "#7a1fa2",
    buttonBorderRadius: "6px",
  },
};

export default chatbotThemes;
